version: '3.11'

services:
  backend:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code

    ports:
      - 8000:8000